#!/usr/bin/env python3
"""Regression tests for preserving stricter review-submission authority bounds."""

import json
import pathlib

from jsonschema import Draft202012Validator

from agent_review_to_artifact import submission_bounds

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "agents" / "schemas" / "review.schema.json"


def main() -> int:
    default_authority, default_human = submission_bounds("No explicit authority override.")
    assert default_authority == "repository-scoped"
    assert default_human is False

    issue_123_style = """
Generated by agent. `human_verification_required: true`. Claims require human verification.
`decision_authority: none`. This review does not change lifecycle status.
"""
    authority, human_required = submission_bounds(issue_123_style)
    assert authority == "none"
    assert human_required is True

    plain_machine_readable = "decision_authority: none\nhuman_verification_required: true\n"
    authority, human_required = submission_bounds(plain_machine_readable)
    assert authority == "none"
    assert human_required is True

    artifact = {
        "review_id": "AR-0123",
        "idea_id": "HK-0056",
        "role": "skeptic",
        "reviewer_id": "regression-agent",
        "source_issue": "https://github.com/Svyable/human-kind/issues/123",
        "created_at": "2026-09-03",
        "summary": "A regression artifact preserving stricter submitter-declared bounds.",
        "findings": ["Detection and ecological inference remain distinct claims."],
        "sources": ["https://github.com/Svyable/human-kind/issues/123"],
        "uncertainties": ["The substantive claims remain unverified."],
        "risks": ["Authority widening would corrupt contribution provenance."],
        "recommended_status": "needs-evidence",
        "next_action": "Obtain independent human verification before treating claims as verified.",
        "generated_by": "agent",
        "review_requirement": "independent",
        "verification_status": "unverified",
        "claims_requiring_verification": True,
        "source_links_required": True,
        "human_verification_required": True,
        "decision_authority": "none",
    }
    schema = json.loads(SCHEMA.read_text())
    Draft202012Validator(schema).validate(artifact)

    print("Review submission-bound preservation regression tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
