#!/usr/bin/env python3
"""Regression tests for preserving stricter review-submission authority bounds."""

from agent_review_to_artifact import submission_bounds


def main() -> int:
    default_authority, default_human = submission_bounds("No explicit authority override.")
    assert default_authority == "repository-scoped"
    assert default_human is False

    issue_123_style = """
Generated by agent. `human_verification_required: true`. Claims require human verification.
`decision_authority: none`. This review does not change lifecycle status.
"""
    authority, human_required = submission_bounds(issue_123_style)
    assert authority == "none"
    assert human_required is True

    plain_machine_readable = "decision_authority: none\nhuman_verification_required: true\n"
    authority, human_required = submission_bounds(plain_machine_readable)
    assert authority == "none"
    assert human_required is True

    print("Review submission-bound preservation regression tests passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
